# -*- coding: utf-8 -*-
"""Aprendizaje_maquina.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zc1OmcIkKU-0LrWxvoBcxAHZOPIR2T6w

Omar Rodríguez Montiel - A01750836

[Dataset Diabetes - Kaggle](https://www.kaggle.com/datasets/nanditapore/healthcare-diabetes)

# Dependencias
"""

import os

# Manejo de datos
import pandas as pd
import numpy as np

# Visualización
import matplotlib.pyplot as plt
import seaborn as sns

# Modelos de aprendizaje
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix, silhouette_score
from sklearn.preprocessing import MinMaxScaler, StandardScaler

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans, DBSCAN
from sklearn.mixture import GaussianMixture

# Herramientas extra
os.system('pip install kneed')
from kneed import KneeLocator
from itertools import combinations
from tqdm.autonotebook import tqdm

"""# Importar datos"""

df = pd.read_csv('/content/Healthcare-Diabetes.csv', index_col='Id')
df.head()

"""# Exploración de los datos"""

df.Outcome.plot.hist()

df.describe().T

for col in df.columns[:-1]:
    plt.title(col)
    df[col].plot.hist() #plotting the histogram with Pandas
    plt.show()

"""# Pre-procesamiento"""

numeric_cols = [col for col in df.columns if df[col].nunique() > 2]
categoric_cols = [col for col in df.columns if col not in numeric_cols]

norm = df.copy()
scaled = df.copy()

mms = MinMaxScaler()
ss = StandardScaler()

for col in numeric_cols:
    norm[col] = mms.fit_transform(norm[[col]])
    scaled[col] = ss.fit_transform(scaled[[col]])

display(norm.describe().T)
display(scaled.describe().T)

sns.heatmap(df.corr())

"""# Separación de los datos"""

X, y = norm.iloc[:, :-1], norm.iloc[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

evaluate = lambda y_true, y_pred, label='': print(f'{label}\t Accuracy = {accuracy_score(y_true, y_pred)*100:.2f}%    \t F1 Score = {f1_score(y_true, y_pred)*100:.2f}%')

def visualize_metrics(y_true, y_pred):
    cm = confusion_matrix(y_true, y_pred)
    print(classification_report(y_true,y_pred))

    sns.heatmap(cm, annot=True, fmt='d').set_title('Confusion matrix')

"""# Aprendizaje supervisado

### **Árbol de decisión**
(visto en clase)

#### Entrenamiento
"""

param_grid = {
    'criterion': ['gini', 'entropy', 'log_loss'],
    'max_depth': list(range(3, 16))
}

# Buscar mejor configuración de hiperparámetros y selección de datos
grid = GridSearchCV(DecisionTreeClassifier(), param_grid, cv=5, scoring='accuracy')
grid.fit(X_train, y_train)
clf = grid.best_estimator_

y_pred_train = clf.predict(X_train)
y_pred = clf.predict(X_test)

evaluate(y_train, y_pred_train, 'Train data --')
evaluate(y_test, y_pred, 'Test data --')

"""#### Visualización"""

visualize_metrics(y_train, y_pred_train) # Matriz de confusión de datos de entrenamiento

visualize_metrics(y_test, y_pred) # Matriz de confusión de datos de prueba

"""### **Bosques Aleatorios**
(no visto en clase)

#### Entrenamiento
"""

rf = RandomForestClassifier(criterion=clf.get_params()['criterion'], max_depth=clf.get_params()['max_depth'], n_estimators=300)
rf.fit(X_train, y_train)

y_pred_train = rf.predict(X_train)
y_pred = rf.predict(X_test)

evaluate(y_train, y_pred_train, 'Train data --')
evaluate(y_test, y_pred, 'Test data --')

"""#### Visualización"""

visualize_metrics(y_train, y_pred_train) # Matriz de confusión de datos de entrenamiento

visualize_metrics(y_test, y_pred) # Matriz de confusión de datos de prueba

"""# Aprendizaje no supervisado

### Exploración de los datos
"""

def plot_tsne(X, y):
    from sklearn.manifold import TSNE
    tsne = TSNE(perplexity=5, n_components=2, init="pca", n_iter=5000)

    coords = tsne.fit_transform(X)

    X_, y_ = list(zip(*coords))
    plt.figure(figsize=(10, 6))
    p = sns.scatterplot(x=X_, y=y_)
    plt.grid(True)
    plt.show()

    return coords

plot_tsne(X, y)

"""### **KMeans**
(visto en clase)

#### Selección de datos
"""

# Combinaciones de columnas del dataset del 2 al n columnas
col_combinations = [comb for i in range(2, len(X.columns) + 1) for comb in list(combinations(X.columns, r=i))]

plt.style.use("seaborn-v0_8-bright")

kmeans_kwargs = {
        "init": "random",
        "n_init": 10,
        "max_iter": 300,
        "random_state": 42,
        }

k2_cols = []
for cols in tqdm(col_combinations, total=len(col_combinations)):
    X_ = norm.loc[:, list(cols)]

    sse = [] # Suma de errores cuadrados
    silhouette_coefficients = []

    kmeans = KMeans(n_clusters=1, **kmeans_kwargs)
    kmeans.fit(X_)
    sse.append(kmeans.inertia_)

    for k in range(2, 11):
        kmeans = KMeans(n_clusters=k, **kmeans_kwargs)
        kmeans.fit(X_)

        sse.append(kmeans.inertia_)
        silhouette_coefficients.append(silhouette_score(X_, kmeans.labels_))

    best_k_elbow = KneeLocator(range(1, 11), sse, curve="convex", direction="decreasing").elbow # Mejor k con método del codo
    best_k_sil = max(enumerate(silhouette_coefficients, start=2), key=lambda x: x[1])[0] # Mejor K con método de la silueta

    if not (best_k_elbow == best_k_sil == 2): continue # Ignorar combinación de columnas si no cumplen con la k deseada
    k2_cols.append(cols) # Añadir combinación de columnas que cumplen con el criterio

    # Visualización
    print(f'Usando = {cols}')
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    axes[0].plot(range(1, 11), sse, marker='o')
    axes[0].plot(best_k_elbow, sse[best_k_elbow - 1], marker='o', color='red')
    axes[0].text(best_k_elbow, sse[best_k_elbow - 1], '   Mejor k = ' + str(best_k_elbow), color='red')
    plt.xticks(range(1, 11))
    axes[0].set_title('Método del codo')

    axes[1].plot(range(2, 11), silhouette_coefficients, marker='o')
    axes[1].plot(best_k_sil, silhouette_coefficients[best_k_sil - 2], marker='o', color='red')
    axes[1].text(best_k_sil, silhouette_coefficients[best_k_sil - 2], '   Mejor k = ' + str(best_k_sil), color='red')
    plt.xticks(range(2, 11))
    axes[1].set_title('Método de la silueta')

    plt.show()

"""#### Entrenamiento"""

X_ = norm.loc[:, k2_cols[1]]
kmeans = KMeans(n_clusters=2, **kmeans_kwargs)
kmeans.fit(X_)

evaluate(y, kmeans.labels_, str(k2_cols[1]) + '\t---')

"""#### Visualización"""

visualize_metrics(y, kmeans.labels_) # Matriz de confusión para comparar

"""### **Modelo de Mezcla Gaussiana**
(no visto en clase)

#### Selección de datos
"""

plt.style.use("seaborn-v0_8-bright")

k2_cols = []
for cols in tqdm(col_combinations, total=len(col_combinations)):
    X_ = scaled.loc[:, list(cols)] # Usar datos escalados (distribución gaussiana)

    bics = [] # Criterio de información bayesiana
    silhouette_coefficients = []

    gmm = GaussianMixture(n_components=1, random_state=42)
    gmm.fit(X_)
    bics.append(gmm.bic(X_))

    for k in range(2, 11):
        gmm = GaussianMixture(n_components=k, random_state=42)
        gmm.fit(X_)
        bics.append(gmm.bic(X_))
        score = silhouette_score(X_, gmm.predict(X_))
        silhouette_coefficients.append(score)

    best_k_elbow = KneeLocator(range(1, 11), bics, curve="convex", direction="decreasing").elbow # Mejor k con método del codo
    best_k_sil = max(enumerate(silhouette_coefficients, start=2), key=lambda x: x[1])[0] # Mejor K con método de la silueta

    if not (best_k_elbow == best_k_sil == 2): continue # Ignorar combinación de columnas si no cumplen con la k deseada
    k2_cols.append(cols) # Añadir combinación de columnas que cumplen con el criterio

    # Visualización
    print(f'Usando = {cols}')
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    axes[0].plot(range(1, 11), bics, marker='o')
    axes[0].plot(best_k_elbow, bics[best_k_elbow - 1], marker='o', color='red')
    axes[0].text(best_k_elbow, bics[best_k_elbow - 1], '   Mejor k = ' + str(best_k_elbow), color='red')
    plt.xticks(range(1, 11))
    axes[0].set_title('Método del codo')

    axes[1].plot(range(2, 11), silhouette_coefficients, marker='o')
    axes[1].plot(best_k_sil, silhouette_coefficients[best_k_sil - 2], marker='o', color='red')
    axes[1].text(best_k_sil, silhouette_coefficients[best_k_sil - 2], '   Mejor k = ' + str(best_k_sil), color='red')
    plt.xticks(range(2, 11))
    axes[1].set_title('Método de la silueta')

    plt.show()

"""#### Entrenamiento"""

cols = ('Pregnancies', 'Glucose', 'SkinThickness') # Combinación de columnas arbitrariamente extraída de 'k2_cols'
X_ = scaled.loc[:, cols]

gmm = GaussianMixture(n_components=2, random_state=42)
gmm.fit(X_)

pred_labels = gmm.predict(X_)
evaluate(y, pred_labels, str(cols) + '\t ---')

"""#### Visualización"""

visualize_metrics(y, pred_labels)